### ISSUE TITLE
Bugs/feature requests

### ISSUE THREAD

**Issue by mayeaux** [hamidb80/subtitle-edtior#14]
Two features you added look really good!

I think it's pretty close to being very functional. 

I'll add the features that to me are still missing to make it very intuitive:

1) Spacebar should start/pause video (helps get to the exact point when changing subtitle timings)

2) Ability to drag the timeline to move the video forward/backwards
![Screen Shot 2023-04-21 at 2 57 05 PM](https://user-images.githubusercontent.com/7200471/233641759-5e91464e-895e-478e-bad6-5cc05033ec26.JPG)

In this screenshot, if I put my cursor over the 17 second mark it shows a pointer, but I should be able to drag starting at that number and move the timeline backwards or forwards and have it change the video time.

Also, you can see there's a bug, if the video is too long and you zoom in the timeline stacks on top of eachother and it bugs the functionality (I changed the dom manually in that screenshot)

Also, I think you should be able to zoom in past what is currently the limit of 100 to be able to have precision with the timestamps.

Also, I think you should be able to drag to change the start/end timing of the subtitles without selecting the timestamp. Clicking it each time is  not very intuitive, I think it would be better to be able to grab the ends without it.

Also, when you are dragging to change the duration, you should be able to see the space that it is filling (or it should show that it's being shortened). It should track with the dotted redline above it when you drag. Same thing with the drag, you should be able to see it as it's moving rather than it jumping (will help to line up ends/beginnings with certain time segments etc)

Also, I think this should be widened. Sometimes the subtitles can be longer and there's extra space around so may as well use it. (I like the feature to click to change from right-to-left text and left-to-right languages!)
![Screen Shot 2023-04-21 at 3 01 51 PM](https://user-images.githubusercontent.com/7200471/233642620-9c59631e-e83c-4320-a2ef-ea0715cdbff9.JPG)

Also, I think a single click should deselect the subtitle the same way a single click selects it. I like how it repeats when it's selected but that will help to quickly unselect it, the escape button is not super intuitive.

Also, clicking anywhere on the video should start/stop it. Spacebar is the best solution but at least that will be much better since the video will have to be stopped/restarted a lot.

Anyways, I think you have a very solid foundation here, it's up to you if you want to implement these but I looked far and wide and there's no real good online subtitle editor solutions so I think this could become the default open source online subtitle editor, it's the only one I'm interested in using at the moment.

Thanks for your work, cheers!

**Comment by hamidb80** [comment]
> 1. Spacebar should start/pause video (helps get to the exact point when changing subtitle timings)

`ctrl+enter` does this, using space as play/pause is not a good idea because you cannot type the caption and watch the video at the aame time.


----------
* [ ] Ability to drag the timeline to move the video forward/backwards
* [x] double timelines when video is too long
* [ ] more precise timeline when zoom is more than 70%
* [ ] drag to change the start/end timing of the subtitles without selecting the timestamp
* [ ] clicking anywhere on the video should start/stop it
* [ ] single click should deselect the subtitle the same way a single click selects it
* [ ] widen the caption text editor
* [ ] you should be able to see it as it's moving rather than it jumping (caption)
* [ ] you are dragging to change the duration, you should be able to see the space that it is filling

**Comment by hamidb80** [comment]
> Anyways, I think you have a very solid foundation here, it's up to you if you want to implement these but I

Thanks! Your donations can be a motivation for my projects
