### ISSUE TITLE
Bugs/feature requests

### ISSUE THREAD

**Issue by moisestohias** [hamidb80/subtitle-edtior#15]
You've done nice work here.

## Issues: 
- For whatever reason, most of the zoom values collapses (shrinks) the box containing the transcription.

## Suggestions for UI Enhancement:

- Enlarge the timeline bar (text transcription bar) to ensure complete sentence display.
- Incorporate a waveform display beneath the text to offer a visual aid for easier transcription.
- Enable direct editing within the selected box (square with current transcription) instead of a separate editing box.
- Integrate the progress bar into the timeline bar for streamlined progress tracking.
- Relocate the "save as file" option to the top navigation bar, freeing space for the timeline and waveform, while dedicating the bottom section solely for editing.

**Comment by hamidb80** [comment]
> to ensure complete sentence display

Doing this would violates timing of the caption (for e.g. lets say a caption starts from 00:01 to 00:02, exapnding it to show all of its text would make it from 00:01 until 00:03)

> Incorporate a waveform display

I really like this idea but I think that is a heavy process and requires a server or using web-assembly. ( BTW if you know a library that does this, please let me know! )

> Enable direct editing within the selected box

Again like 1, the caption box is so tiny 

> Integrate the progress bar into the timeline bar for streamlined progress tracking

I'm not sure what does this mean, can you explain more?

**Comment by moisestohias** [comment]
Thanks for the prompt answer.

> > to ensure complete sentence display
> 
> Doing this would violates timing of the caption (for e.g. lets say a caption starts from 00:01 to 00:02, exapnding it to show all of its text would make it from 00:01 until 00:03)

You don't have to display the full sentence, you only show the full sentence when the user is zoomed in, and the box is large enough to fit the full sentence. Otherwise it must be abbreviated with dots ...
Or at least make box larger (add more height) to display more text

> > Incorporate a waveform display
> 
> I really like this idea but I think that is a heavy process and requires a server or using web-assembly. ( BTW if you know a library that does this, please let me know! )

Me as well have the same concern, I've tried wavesurfer-js library before, it worked well for me, it doesn't seem to add a lot of overhead, here is an [example](https://wavesurfer-js.org/examples/#regions.js), and it doesn't require a server. [doc](wavesurfer-js.org/docs/)

> > Enable direct editing within the selected box
> 
> Again like 1, the caption box is so tiny

This will be possible if the above is achieved,

> > Integrate the progress bar into the timeline bar for streamlined progress tracking

> I'm not sure what does this mean, can you explain more?

Having the progress bar detached from the transcription editing timeline is bit weird (bad user experience) 

Also check [Descript](youtube.com/@Descript/videos)

**Comment by moisestohias** [comment]
example, just the boxes containing the text to be wider

![2](https://github.com/hamidb80/subtitle-editor/assets/48728934/ac529ee6-08fb-4f3f-9bca-c82856119c4d)

**Comment by hamidb80** [comment]
> here is an example, and it doesn't require a server. doc

Hey, Ive tried wavesurfer.js
But it does not work on long files

**Comment by hamidb80** [comment]
do you know any other audio analyzer libraries?
