### ISSUE TITLE
subtitiletimeline  scroll and mouse click subtitletimeline issue in laravel when i am use 

### ISSUE THREAD

**Issue by BabarEplanet** [hamidb80/subtitle-edtior#16]
![Screenshot 2024-02-23 192748](https://github.com/hamidb80/subtitle-editor/assets/157487308/0c63ecbc-b6f6-4644-8f65-884f4d4d16c2)

warning are attached i thing some issue in my code would you like to help to resolve it

**Comment by BabarEplanet** [comment]
![image](https://github.com/hamidb80/subtitle-editor/assets/157487308/514b5578-33cc-499d-ae8e-77fafb1b28b2)

when i am clicking on black bar its store from 0 not start 
click area

**Comment by hamidb80** [comment]
Hey, can you record a video or a gif showing the problem?

**Comment by BabarEplanet** [comment]
@hamidb80  yes sure i will share an small demo video of editor

**Comment by BabarEplanet** [comment]
@hamidb80  one thing more is it posible two thing in your editor 
1. 
![image](https://github.com/hamidb80/subtitle-editor/assets/157487308/af5ab548-5ade-4998-a9ab-5f8116087269)

this time of time fram in left of the video 
2.
![image](https://github.com/hamidb80/subtitle-editor/assets/157487308/8c1b5503-e796-4f12-a4ef-d0eb1142a1bb)

**Comment by BabarEplanet** [comment]
https://github.com/hamidb80/subtitle-editor/assets/157487308/94152a33-d1a5-4cdb-8a0a-990e46a8cf38

hey dear here is video 
when i am click the bar its start video  form start point not on clicking point

**Comment by hamidb80** [comment]
Seems like some of the fonts and styles are missing

**Comment by hamidb80** [comment]
Seems like some of the fonts and styles are missing in your clone

Make sure they are loaded

**Comment by BabarEplanet** [comment]
@hamidb80 greate let me check and i will feedback you
