### ISSUE TITLE
Missing the functionality to drag subtitles to change their length

### ISSUE THREAD

**Issue by mayeaux** [hamidb80/subtitle-edtior#7]
Without being able to drag the ends of the subtitles to change the length the value is pretty limited no offense. Manually entering the values is very clunky. I might deploy this for freesubtitles.ai but that is definitely a blocker on that front.

**Comment by hamidb80** [comment]
Hey, 
When do you want this feature to be ready?

Is it OK next 2 weeks ?

**Comment by hamidb80** [comment]
Do you want draging the start/end of caption to extend/limit the timing or moving the caption? Or both?

**Comment by mayeaux** [comment]
Probably both would be good. Yeah if you have a chance that would be great. I looked around for open source subtitle editors today and there wasn't much to choose from so I'd probably deploy yours if those features were available

**Comment by hamidb80** [comment]
https://user-images.githubusercontent.com/33871336/230682544-024f3f8e-f281-40d4-a702-56e219063988.mp4


I've made some changes but broke the undo/redo, is that what you want?

if yes, I fix undo/redo

**Comment by hamidb80** [comment]
note that the move applies on mouse release [it's not visible in the video because of low frame-rate ]

**Comment by mayeaux** [comment]
Yup that looks good! I will try out the code sometime today if I have the chance

**Comment by mayeaux** [comment]
Also would be great if I could load the video and srt automatically through a query param, such as 
https://editor.freesubtitles.ai?video=https://freesubtitles.ai/video.mp4&caption=https://freesubtitles.ai/caption.srt , and then have it start automatically in the studio. I think with those features (and the new move/edit lengths from the mouse) it would be enough for me to ship it

**Comment by hamidb80** [comment]
you can now test it.

https://hamidb80.github.io/subtitle-editor/
