### ISSUE TITLE
load the video and srt automatically through a query param

### ISSUE THREAD

**Issue by hamidb80** [hamidb80/subtitle-edtior#9]
Also would be great if I could load the video and srt automatically through a query param, such as 
https://editor.freesubtitles.ai?video=https://freesubtitles.ai/video.mp4&caption=https://freesubtitles.ai/caption.srt , and then have it start automatically in the studio. I think with those features (and the new move/edit lengths from the mouse) it would be enough for me to ship it

_Originally posted by @mayeaux in https://github.com/hamidb80/subtitle-editor/issues/7#issuecomment-1500820448_

**Comment by hamidb80** [comment]
https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript

**Comment by hamidb80** [comment]
works with `?video=URL&subtitle=URL`
like:
```
https://hamidb80.github.io/subtitle-editor/?video=https://hajifirouz14.asset.aparat.com/aparat-video/f0f7de29d06b8e4673109d0c11dd84c951366628-480p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IjY5ODBhNmNhNGM5OTEzNTcyM2Y1N2Q1ODIyZTJhYzc1IiwiZXhwIjoxNjgxMTQ3MDQzLCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.Vb0JBD078GHr6Ibs_esvWOXV5BorSMB7_temXI8igQ8&subtitle=https://raw.githubusercontent.com/CEShahed/cs-persian-subtitles/main/subtitles/a-construction-worker-who-wanted-to-marry-princess.srt
```

![image](https://user-images.githubusercontent.com/33871336/230900949-372ddf83-75d3-4f1d-b81e-eed4c730ea4d.png)

**Comment by hamidb80** [comment]
@mayeaux note that you should remove `basename` attribute in order to make it work in `editor.freesubtitles.ai/`.

https://github.com/hamidb80/subtitle-editor/blob/9220d35e75dff1d1a21bb58e04bf60331a9d3157/src/App.tsx#L12

I've added this line to work in Github-pages in url: `https://hamidb80.github.io/subtitle-editor/`

**Comment by mayeaux** [comment]
Nice!
